[package]
name = "crab-shortener"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-actix-native-tls" , "sqlite" ] }
actix-web = "4"
actix-files = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"

[build-dependencies]
fs_extra = "1.2.0"
